🐛 Update bottle-test.yml (#83)

diff --git a/.github/workflows/bottle-test.yml b/.github/workflows/bottle-test.yml
--- a/.github/workflows/bottle-test.yml
+++ b/.github/workflows/bottle-test.yml
@@ -18,7 +18,7 @@ jobs:
 
     - name: Check for launch line
       run: |
-        if ! grep -q -E "^([^#])*run\(host='0\.0\.0\.0', port=80\)" main.py; then echo "Launch line not found in main.py"; exit 1; fi
+        if ! grep -q -E "^([^#])*run\(host=\"0\.0\.0\.0\", port=80\)" main.py; then echo "Launch line not found in main.py"; exit 1; fi
 
     - name: Install dependencies
       run: |
@@ -27,7 +27,7 @@ jobs:
         
     - name: Modify launch line
       run: |
-        sed -i 's/run(host=\x270.0.0.0\x27, port=80)/run(host=\x27localhost\x27, port=8080, debug=True)/' main.py
+        sed -i 's/run(host="0\.0\.0\.0", port=80)/run(host="localhost", port=8080, debug=True)/' main.py
 
     - name: Launch development server
       run: |
