Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -21,4 +21,9 @@ jobs:
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Analysing the code with pylint
       run: |
-        pylint $(git ls-files '*.py')
+        pylint_result=$(pylint $(git ls-files '*.py') | grep -oP 'Your code has been rated at \K[0-9.]+')
+        echo "Pylint score: $pylint_result"
+        if (( $(echo "$pylint_result < 8" | bc -l) )); then
+          echo "Pylint score is below 8. Exiting with error."
+          exit 1
+        fi
