Update python-test.yml

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -16,14 +16,14 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Check for launch line
+      run: |
+        if ! grep -q "run(host='0.0.0.0', port=80)" main.py; then echo "Launch line not found in main.py"; exit 1; fi
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-
-    - name: Check for launch line
-      run: |
-        if ! grep -q "run(host='0.0.0.0', port=80)" main.py; then echo "Launch line not found in main.py"; exit 1; fi
 
     - name: Modify launch line
       run: |
